export enum Path {
  HOME = '/',
  ABOUT = '/about',
  SKILLS = '/skills',
  EXPERIENCE = '/experience',
  PORTFOLIO = '/portfolio',
  CONTACT = '/contact',
}

export enum Title {
  HOME = 'Главная',
  ABOUT = 'Обо мне',
  SKILLS = 'Навыки',
  EXPERIENCE = 'Опыт',
  PORTFOLIO = 'Портфолио',
  CONTACT = 'Контакты',
}

export enum Company {
  MVIDEO = 'М.Видео',
  EVERPOINT = 'Эверпоинт',
  SEVEN_GLYPHS = '7 glyphs Ltd.',
  TSFTD = 'ТехноСофт Диджитал',
}

export enum Technology {
  JS = 'JavaScript',
  TS = 'TypeScript',
  REACT = 'React',
  REDUX = 'Redux',
  MOBX = 'MobX',
  PREACT = 'Preact',
  VUE = 'Vue.js',
  SVELTE = 'Svelte',
  APOLLO = 'Apollo Client',
  JQUERY = 'jQuery',
  HTML = 'HTML',
  SVG = 'SVG',
  JSX = 'JSX',
  PUG = 'Pug',
  HANDLEBARS = 'Handlebars',
  MARKDOWN = 'Markdown',
  BLADE = 'Blade',
  CSS = 'CSS',
  BEM = 'BEM',
  SASS = 'Sass',
  MUI = 'Material-UI',
  MODULES = 'CSS Modules',
  STYLED = 'styled-components',
  REACTSTRAP = 'reactstrap',
  ANT = 'Ant Design',
  MATERIALIZE = 'Materialize',
  BOOTSTRAP = 'Bootstrap',
  SEMANTIC = 'Semantic UI',
  EMAILS = 'Foundation for Emails',
  NPM = 'NPM',
  YARN = 'Yarn',
  WEBPACK = 'webpack',
  GULP = 'Gulp',
  PARCEL = 'Parcel',
  CRA = 'Create React App',
  GATSBY = 'Gatsby',
  NEXT = 'Next.js',
  NUXT = 'Nuxt.js',
  BABEL = 'Babel',
  PRETTIER = 'Prettier',
  ESLINT = 'ESLint',
  STORYBOOK = 'Storybook',
  BIT = 'Bit',
  JEST = 'Jest',
  VSCODE = 'Visual Studio Code',
  ITERM = 'iTerm2',
  GIT = 'Git',
  DEVTOOLS = 'Chrome DevTools',
  ZEPLIN = 'Zeplin',
  SKETCH = 'Sketch',
  FIGMA = 'Figma',
  PHOTOSHOP = 'Photoshop',
  OPTIM = 'ImageOptim',
  MAC = 'macOS Catalina',
  NODE = 'Node.js',
  MONGO = 'MongoDB',
  MYSQL = 'MySQL',
  PHP = 'PHP',
  LARAVEL = 'Laravel',
}
